name: deploy-template-branch

on:
  push:
    branches:
      - "deploy-template"

jobs:
  build:
    name: create-release
    runs-on: ubuntu-latest

    steps:
      - name: .Net Build
        # You may pin to the exact commit or the version.
        # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
        uses: EasyDesk/action-dotnet-build@v1.0.0
        #with:
          # Additional build arguments to pass to 'dotnet build'.
          #build-args: # optional
          # The build configuration to use (defaults to 'Release').
          #build-configuration: # optional, default is Release
          # The path to the project or solution to build (defaults to the current directory).
          #path: # optional, default is.
            
      
